const neverHaveIEverQuestions = [
  "Never have I ever skipped school.",
  "Never have I ever lied to my parents.",
  "Never have I ever cheated on a test.",
  "Never have I ever been in a fight.",
  "Never have I ever broken a bone.",
  "Never have I ever been caught sneaking out.",
  "Never have I ever eaten something weird.",
  "Never have I ever been on TV.",
  "Never have I ever gotten a tattoo.",
  "Never have I ever gone skinny dipping.",
  "Never have I ever lied about my age.",
  "Never have I ever been in love.",
  "Never have I ever been to a concert.",
  "Never have I ever fainted.",
  "Never have I ever gotten lost in a foreign country.",
  "Never have I ever pulled an all-nighter.",
  "Never have I ever been on a blind date.",
  "Never have I ever cried at a movie.",
  "Never have I ever eaten an entire pizza by myself.",
  "Never have I ever played a prank on someone.",
  "Never have I ever lied to a friend.",
  "Never have I ever gone camping.",
  "Never have I ever been to a wedding.",
  "Never have I ever gotten a speeding ticket.",
  "Never have I ever been in a car accident.",
  "Never have I ever been on a roller coaster.",
  "Never have I ever been to a theme park.",
  "Never have I ever lost my wallet.",
  "Never have I ever been on a plane.",
  "Never have I ever gotten a piercing.",
  "Never have I ever been to a funeral.",
  "Never have I ever been to a fancy restaurant.",
  "Never have I ever been to a spa.",
  "Never have I ever been to a sports game.",
  "Never have I ever been to a music festival.",
  "Never have I ever been to a comedy show.",
  "Never have I ever been to a magic show.",
  "Never have I ever been to a dance club.",
  "Never have I ever been to a karaoke bar.",
  "Never have I ever been to a poetry reading.",
  "Never have I ever been to a book signing.",
  "Never have I ever been to a cooking class.",
  "Never have I ever been to a painting class.",
  "Never have I ever been to a pottery class.",
  "Never have I ever been to a zoo.",
  "Never have I ever been to an aquarium.",
  "Never have I ever been to a vineyard.",
  "Never have I ever been to a brewery.",
  "Never have I ever been to a farmers market.",
  "Never have I ever been to a flea market."
];

const limitedQuestions = neverHaveIEverQuestions.sort(() => Math.random() - 0.5).slice(0, 20);

export default limitedQuestions;
