// Import utility function for cleaner shuffling
import { getRandomSubset, shuffleArray } from '../../utils/gameUtils';

const truthOrDareQuestions = [
    { type: "truth", text: "What is your biggest fear?" },
    { type: "truth", text: "Have you ever lied to a friend?" },
    { type: "truth", text: "What is your most embarrassing moment?" },
    { type: "truth", text: "Who was your first crush?" },
    { type: "truth", text: "What is a secret you’ve never told anyone?" },
    { type: "truth", text: "What’s the worst gift you’ve ever received?" },
    { type: "truth", text: "What’s the most childish thing you still do?" },
    { type: "truth", text: "Have you ever cheated on a test?" },
    { type: "truth", text: "What’s the most trouble you’ve gotten into at school?" },
    { type: "truth", text: "What’s a habit you wish you could break?" },
    { type: "dare", text: "Do your best dance move for 30 seconds." },
    { type: "dare", text: "Sing the chorus of your favorite song." },
    { type: "dare", text: "Do 10 jumping jacks right now." },
    { type: "dare", text: "Speak in an accent for the next round." },
    { type: "dare", text: "Let someone else send a text from your phone." },
    { type: "dare", text: "Act like your favorite animal for 1 minute." },
    { type: "dare", text: "Share a funny story from your childhood." },
    { type: "dare", text: "Draw a self-portrait in 1 minute." },
    { type: "dare", text: "Imitate a celebrity until someone guesses who it is." },
    { type: "dare", text: "Do your best impression of a teacher." },
    { type: "truth", text: "What is the most recent lie you told?" },
    { type: "truth", text: "What is your guilty pleasure?" },
    { type: "truth", text: "Have you ever broken the law?" },
    { type: "truth", text: "What is the most expensive thing you own?" },
    { type: "truth", text: "Who is your secret hero?" },
    { type: "truth", text: "What is the worst thing you’ve ever done?" },
    { type: "truth", text: "Have you ever stolen something?" },
    { type: "truth", text: "What is your biggest regret?" },
    { type: "truth", text: "What is your biggest insecurity?" },
    { type: "truth", text: "What is the most awkward date you’ve ever been on?" },
    { type: "truth", text: "Have you ever been caught cheating?" },
    { type: "truth", text: "What is the most childish thing you’ve done recently?" },
    { type: "truth", text: "What’s the worst thing you’ve said to someone?" },
    { type: "truth", text: "Have you ever pretended to be sick to get out of something?" },
    { type: "truth", text: "What’s the most trouble you’ve gotten into at home?" },
    { type: "truth", text: "Have you ever lied about your age?" },
    { type: "truth", text: "What’s the weirdest dream you’ve ever had?" },
    { type: "truth", text: "What’s the most embarrassing thing in your room?" },
    { type: "truth", text: "Have you ever been rejected by someone?" },
    { type: "truth", text: "What’s the worst job you’ve ever had?" },
    { type: "truth", text: "Have you ever had a crush on a teacher?" },
    { type: "truth", text: "What’s the most expensive thing you’ve lost?" },
    { type: "truth", text: "Have you ever lied to your parents?" },
    { type: "truth", text: "What’s the most useless talent you have?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in public?" },
    { type: "truth", text: "Have you ever been caught doing something you shouldn’t?" },
    { type: "truth", text: "What’s the worst meal you’ve ever cooked?" },
    { type: "truth", text: "What’s the most ridiculous argument you’ve had?" },
    { type: "truth", text: "Have you ever been in love?" },
    { type: "truth", text: "What’s the most annoying habit you have?" },
    { type: "truth", text: "Have you ever lied to get out of trouble?" },
    { type: "truth", text: "What’s the worst thing you’ve done at work?" },
    { type: "truth", text: "What’s the most embarrassing photo of you?" },
    { type: "truth", text: "Have you ever been jealous of a friend?" },
    { type: "truth", text: "What’s the most childish thing you still do?" },
    { type: "truth", text: "Have you ever lied about liking a gift?" },
    { type: "truth", text: "What’s the worst date you’ve ever been on?" },
    { type: "truth", text: "Have you ever lied to your best friend?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done for money?" },
    { type: "truth", text: "Have you ever cheated in a game?" },
    { type: "truth", text: "What’s the weirdest thing you’ve ever eaten?" },
    { type: "truth", text: "Have you ever been caught sneaking out?" },
    { type: "truth", text: "What’s the most embarrassing nickname you’ve had?" },
    { type: "truth", text: "Have you ever lied to a teacher?" },
    { type: "truth", text: "What’s the worst grade you’ve ever gotten?" },
    { type: "truth", text: "Have you ever been in a fight?" },
    { type: "truth", text: "What’s the most embarrassing song you like?" },
    { type: "truth", text: "Have you ever lied about your homework?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of a crush?" },
    { type: "truth", text: "Have you ever lied to get something you wanted?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a sibling?" },
    { type: "truth", text: "Have you ever been caught lying?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done at a party?" },
    { type: "truth", text: "Have you ever lied about your feelings?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a friend?" },
    { type: "truth", text: "Have you ever lied to avoid someone?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done at school?" },
    { type: "truth", text: "Have you ever lied to get out of a date?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a stranger?" },
    { type: "truth", text: "Have you ever lied to get a job?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your parents?" },
    { type: "truth", text: "Have you ever lied to get out of work?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a pet?" },
    { type: "truth", text: "Have you ever lied to get out of trouble at home?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your family?" },
    { type: "truth", text: "Have you ever lied to get out of a family event?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a neighbor?" },
    { type: "truth", text: "Have you ever lied to get out of a responsibility?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your boss?" },
    { type: "truth", text: "Have you ever lied to get out of a meeting?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a coworker?" },
    { type: "truth", text: "Have you ever lied to get out of a chore?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your crush?" },
    { type: "truth", text: "Have you ever lied to get out of a promise?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a classmate?" },
    { type: "truth", text: "Have you ever lied to get out of a test?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your teacher?" },
    { type: "truth", text: "Have you ever lied to get out of a presentation?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a stranger online?" },
    { type: "truth", text: "Have you ever lied to get out of a commitment?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your friends?" },
    { type: "truth", text: "Have you ever lied to get out of a group project?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a teammate?" },
    { type: "truth", text: "Have you ever lied to get out of a sports event?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your coach?" },
    { type: "truth", text: "Have you ever lied to get out of a practice?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a competitor?" },
    { type: "truth", text: "Have you ever lied to get out of a competition?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your team?" },
    { type: "truth", text: "Have you ever lied to get out of a challenge?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a friend during a game?" },
    { type: "truth", text: "Have you ever lied to win a game?" },
    { type: "dare", text: "Do a silly walk across the room." },
    { type: "dare", text: "Talk in gibberish for 1 minute." },
    { type: "dare", text: "Pretend to be a robot for 2 minutes." },
    { type: "dare", text: "Make up a song about the person to your left." },
    { type: "dare", text: "Do your best animal sound." },
    { type: "dare", text: "Try to touch your toes for 30 seconds." },
    { type: "dare", text: "Act like a baby for 1 minute." },
    { type: "dare", text: "Do your best evil laugh." },
    { type: "dare", text: "Speak only in rhymes for the next round." },
    { type: "dare", text: "Do a dramatic reading of a random text message." },
    { type: "dare", text: "Pretend to be a famous singer for 1 minute." },
    { type: "dare", text: "Do 5 push-ups." },
    { type: "dare", text: "Make a funny face and hold it for 30 seconds." },
    { type: "dare", text: "Act out a scene from your favorite movie." },
    { type: "dare", text: "Do your best superhero pose." },
    { type: "dare", text: "Pretend to be a news anchor for 1 minute." },
    { type: "dare", text: "Do your best impression of a cartoon character." },
    { type: "dare", text: "Make up a joke and tell it to the group." },
    { type: "dare", text: "Do a silly dance until someone laughs." },
    { type: "dare", text: "Try to juggle three objects." },
    { type: "dare", text: "Speak in a whisper for the next round." },
    { type: "dare", text: "Pretend to be a chef and describe your favorite dish." },
    { type: "dare", text: "Do your best impression of a parent." },
    { type: "dare", text: "Act like you’re on a cooking show for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous athlete." },
    { type: "dare", text: "Pretend to be a dog for 1 minute." },
    { type: "dare", text: "Do your best impression of a villain." },
    { type: "dare", text: "Pretend to be a teacher for 1 minute." },
    { type: "dare", text: "Do your best impression of a superhero." },
    { type: "dare", text: "Act like you’re in a musical for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous singer." },
    { type: "dare", text: "Pretend to be a cat for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous actor." },
    { type: "dare", text: "Act like you’re in a scary movie for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous comedian." },
    { type: "dare", text: "Pretend to be a baby for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous politician." },
    { type: "dare", text: "Act like you’re in a soap opera for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous chef." },
    { type: "dare", text: "Pretend to be a bird for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous scientist." },
    { type: "dare", text: "Act like you’re in a reality show for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous artist." },
    { type: "dare", text: "Pretend to be a fish for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous writer." },
    { type: "dare", text: "Act like you’re in a game show for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous explorer." },
    { type: "dare", text: "Pretend to be a monkey for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous inventor." },
    { type: "dare", text: "Act like you’re in a commercial for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous dancer." },
    { type: "dare", text: "Pretend to be a horse for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous magician." },
    { type: "dare", text: "Act like you’re in a talent show for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous director." },
    { type: "dare", text: "Pretend to be a lion for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous producer." },
    { type: "dare", text: "Act like you’re in a movie trailer for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous model." },
    { type: "dare", text: "Pretend to be a snake for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous photographer." },
    { type: "dare", text: "Act like you’re in a fashion show for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous stylist." },
    { type: "dare", text: "Pretend to be a frog for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous designer." },
    { type: "dare", text: "Act like you’re in a cooking competition for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous baker." },
    { type: "dare", text: "Pretend to be a chicken for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous gardener." },
    { type: "dare", text: "Act like you’re in a gardening show for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous farmer." },
    { type: "dare", text: "Pretend to be a cow for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous chef on TV." },
    { type: "dare", text: "Act like you’re in a food commercial for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous food critic." },
    { type: "dare", text: "Pretend to be a pig for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous food blogger." },
    { type: "dare", text: "Act like you’re in a restaurant for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous waiter." },
    { type: "dare", text: "Pretend to be a duck for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous bartender." },
    { type: "dare", text: "Act like you’re in a bar for 1 minute." },
    { type: "dare", text: "Do your best impression of a famous barista." },
    { type: "dare", text: "Pretend to be a sheep for 1 minute." }
];

// Get 20 random questions of each type and shuffle the final array
const truths = getRandomSubset(
  truthOrDareQuestions.filter(q => q.type === 'truth'), 
  20
);
const dares = getRandomSubset(
  truthOrDareQuestions.filter(q => q.type === 'dare'), 
  20
);
const limitedQuestions = shuffleArray([...truths, ...dares]);

export default limitedQuestions;
