import { getRandomSubset, shuffleArray } from '../../utils/gameUtils';

const truthOrDareQuestions = [
    { type: "truth", text: "What is your biggest fear?" },
    { type: "truth", text: "Have you ever lied to a friend?" },
    { type: "truth", text: "What is your most embarrassing moment?" },
    { type: "truth", text: "Who was your first crush?" },
    { type: "truth", text: "What is a secret you’ve never told anyone?" },
    { type: "truth", text: "What’s the worst gift you’ve ever received?" },
    { type: "truth", text: "What’s the most childish thing you still do?" },
    { type: "truth", text: "Have you ever cheated on a test?" },
    { type: "truth", text: "What’s the most trouble you’ve gotten into at school?" },
    { type: "truth", text: "What’s a habit you wish you could break?" },
    { type: "dare", text: "Do your best dance move for 30 seconds." },
    { type: "dare", text: "Sing the chorus of your favorite song." },
    { type: "dare", text: "Do 10 jumping jacks right now." },
    { type: "dare", text: "Speak in an accent for the next round." },
    { type: "dare", text: "Let someone else send a text from your phone." },
    { type: "dare", text: "Act like your favorite animal for 1 minute." },
    { type: "dare", text: "Share a funny story from your childhood." },
    { type: "dare", text: "Draw a self-portrait in 1 minute." },
    { type: "dare", text: "Imitate a celebrity until someone guesses who it is." },
    { type: "dare", text: "Do your best impression of a teacher." },
    { type: "truth", text: "What is the most recent lie you told?" },
    { type: "truth", text: "What is your guilty pleasure?" },
    { type: "truth", text: "Have you ever broken the law?" },
    { type: "truth", text: "What is the most expensive thing you own?" },
    { type: "truth", text: "Who is your secret hero?" },
    { type: "truth", text: "What is the worst thing you’ve ever done?" },
    { type: "truth", text: "Have you ever stolen something?" },
    { type: "truth", text: "What is your biggest regret?" },
    { type: "truth", text: "What is your biggest insecurity?" },
    { type: "truth", text: "What is the most awkward date you’ve ever been on?" },
    { type: "truth", text: "Have you ever been caught cheating?" },
    { type: "truth", text: "What is the most childish thing you’ve done recently?" },
    { type: "truth", text: "What’s the worst thing you’ve said to someone?" },
    { type: "truth", text: "Have you ever pretended to be sick to get out of something?" },
    { type: "truth", text: "What’s the most trouble you’ve gotten into at home?" },
    { type: "truth", text: "Have you ever lied about your age?" },
    { type: "truth", text: "What’s the weirdest dream you’ve ever had?" },
    { type: "truth", text: "What’s the most embarrassing thing in your room?" },
    { type: "truth", text: "Have you ever been rejected by someone?" },
    { type: "truth", text: "What’s the worst job you’ve ever had?" },
    { type: "truth", text: "Have you ever had a crush on a teacher?" },
    { type: "truth", text: "What’s the most expensive thing you’ve lost?" },
    { type: "truth", text: "Have you ever lied to your parents?" },
    { type: "truth", text: "What’s the most useless talent you have?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in public?" },
    { type: "truth", text: "Have you ever been caught doing something you shouldn’t?" },
    { type: "truth", text: "What’s the worst meal you’ve ever cooked?" },
    { type: "truth", text: "What’s the most ridiculous argument you’ve had?" },
    { type: "truth", text: "Have you ever been in love?" },
    { type: "truth", text: "What’s the most annoying habit you have?" },
    { type: "truth", text: "Have you ever lied to get out of trouble?" },
    { type: "truth", text: "What’s the worst thing you’ve done at work?" },
    { type: "truth", text: "What’s the most embarrassing photo of you?" },
    { type: "truth", text: "Have you ever been jealous of a friend?" },
    { type: "truth", text: "What’s the most childish thing you still do?" },
    { type: "truth", text: "Have you ever lied about liking a gift?" },
    { type: "truth", text: "What’s the worst date you’ve ever been on?" },
    { type: "truth", text: "Have you ever lied to your best friend?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done for money?" },
    { type: "truth", text: "Have you ever cheated in a game?" },
    { type: "truth", text: "What’s the weirdest thing you’ve ever eaten?" },
    { type: "truth", text: "Have you ever been caught sneaking out?" },
    { type: "truth", text: "What’s the most embarrassing nickname you’ve had?" },
    { type: "truth", text: "Have you ever lied to a teacher?" },
    { type: "truth", text: "What’s the worst grade you’ve ever gotten?" },
    { type: "truth", text: "Have you ever been in a fight?" },
    { type: "truth", text: "What’s the most embarrassing song you like?" },
    { type: "truth", text: "Have you ever lied about your homework?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of a crush?" },
    { type: "truth", text: "Have you ever lied to get something you wanted?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a sibling?" },
    { type: "truth", text: "Have you ever been caught lying?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done at a party?" },
    { type: "truth", text: "Have you ever lied about your feelings?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a friend?" },
    { type: "truth", text: "Have you ever lied to avoid someone?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done at school?" },
    { type: "truth", text: "Have you ever lied to get out of a date?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a stranger?" },
    { type: "truth", text: "Have you ever lied to get a job?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your parents?" },
    { type: "truth", text: "Have you ever lied to get out of work?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a pet?" },
    { type: "truth", text: "Have you ever lied to get out of trouble at home?" },
    { type: "truth", text: "What’s the most embarrassing thing you’ve done in front of your family?" },
    { type: "truth", text: "Have you ever lied to get out of a family event?" },
    { type: "truth", text: "What’s the worst thing you’ve done to a neighbor?" },
    { type: "truth", text: "Have you ever lied to get out of a responsibility?" }
];

const truths = getRandomSubset(
  truthOrDareQuestions.filter(q => q.type === 'truth'), 
  20
);
const dares = getRandomSubset(
  truthOrDareQuestions.filter(q => q.type === 'dare'), 
  20
);
const limitedQuestions = shuffleArray([...truths, ...dares]);

export default limitedQuestions;
